# docker-compose.prod.yml - For Production Deployment

services:
  db:
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql 
      - mariadb-backups:/backups
      - ./sql/init:/docker-entrypoint-initdb.d
  
  auth-api:
    image: ghcr.io/yuitokiuchi/auth-api:latest
    restart: always

    ports:
      - "127.0.0.1:3000:3000"

  chat-api:
    image: ghcr.io/yuitokiuchi/chat-api:latest
    restart: always

    ports:
      - "127.0.0.1:4000:4000"
  
  phpmyadmin:
    ports:
      - "8080:80"

volumes:
  mariadb-data:
  mariadb-backups: